[View in Colaboratory](https://colab.research.google.com/github/kamini25singh/assignment/blob/master/Assignment_15.ipynb)

In [0]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [0]:
from sklearn.datasets import load_digits

In [0]:
digit=load_digits()
x=(digit.data)
y=(digit.target)

In [0]:
from sklearn.preprocessing import StandardScaler


In [0]:
x_Std=StandardScaler().fit_transform(x)


In [6]:
x_Std


array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [0]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [0]:
principalComponents = pca.fit_transform(x_Std)


In [0]:
principalDf = pd.DataFrame(data = principalComponents)


In [10]:
principalDf


0         1         2         3         4         5         6   \
0     1.914214 -0.954502 -3.946035  2.028723 -0.267176  0.530327 -1.415325   
1     0.588980  0.924636  3.924755 -1.779850 -0.993433 -0.675650  1.878562   
2     1.302039 -0.317189  3.023333 -2.043376 -2.081158  0.935121 -1.296205   
3    -3.020770 -0.868772 -0.801744 -2.187039 -0.556817  0.727123  0.959762   
4     4.528949 -1.093480  0.973121 -1.419510 -1.715107  1.431594  1.073649   
5    -1.301890 -1.148183 -1.574607 -2.413647 -0.630974  0.740803  1.306800   
6     1.434222 -2.957845  2.831278 -0.076952  0.523031  0.010902  0.983716   
7     0.614240  5.462184  0.658241  0.434429  0.850178 -0.954014 -1.833863   
8    -1.098451 -0.665823 -0.041023 -1.102525 -0.900724  0.755128 -0.966468   
9    -0.537970 -0.777493 -1.568922 -0.759983 -0.121345 -0.600991  0.675179   
10    3.378760 -0.495768 -2.280895  1.429204  0.006573 -0.150585 -0.739175   
11    2.063345  2.016679  1.540476 -4.773151 -2.194261  0.344458  3.084411   
12   -1.937011 -1.815247  2.801367 -0.786547  3.025775 -0.384552 -0.647715   
13   -3.258076  2.149124 -1.615648 -1.798927 -0.745371  1.828827  0.763424   
14    5.458744  0.025132  0.182526 -0.119621 -0.541027  0.104814  1.083122   
15   -3.877036  2.606816  1.858527  5.454027  0.615486  0.988486  3.602251   
16    0.921352 -3.262241  3.401443 -3.227336  1.096492  0.081964 -0.573127   
17    1.415335  1.954479  0.560574 -0.368825 -1.302531 -1.883617 -1.063237   
18   -0.926522  2.253017  1.532929  0.111958 -1.640288  0.261412 -0.069193   
19   -2.370963 -2.931915 -0.381362 -3.232762  2.084192  0.545309 -0.615778   
20    2.001901 -1.319746 -2.570949  0.855346 -0.565536 -1.017711 -0.812002   
21    1.694878  2.075387  0.885988 -4.388594 -1.446109 -0.307273  3.643107   
22   -3.114570 -1.058976  2.451496 -0.547892  0.761752 -0.012653 -1.890062   
23   -1.469418  3.910388 -2.078331 -0.869924  0.203796  0.689528 -0.288167   
24    4.003333 -0.322216  0.587683 -2.740555 -1.513543  0.676056  2.088573   
25   -0.376722  0.525118  1.356041  3.106103  0.926279 -1.029449  1.450075   
26    1.286726 -3.969443  2.542968  0.936671  0.282388  0.352672  1.026761   
27    3.842317  3.478237 -1.569506 -1.675845 -0.274113 -0.345107 -0.150009   
28   -0.166537  0.934111  1.259154 -0.086537 -1.045699  0.362899 -0.877878   
29   -2.014425 -2.376845 -0.707905 -3.515253  1.168342  0.694467  0.206819   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958573 -1.159637  0.645671 -1.495314 -1.408073  0.580223  2.222103   
1768  1.009034 -3.325936 -0.584416  0.907491 -0.665939  0.398975 -1.279985   
1769 -0.542840 -0.492983 -3.138879  0.952805  0.732337 -1.169263  1.900082   
1770 -3.314655  1.510568 -0.820052 -1.838158 -1.474756  1.442500  2.178245   
1771  2.128214 -2.822365  3.623384 -1.087841 -0.085810  0.389349  1.443192   
1772 -1.814030  1.197999 -3.113638 -1.063801 -1.806722  0.021172  1.294923   
1773  1.374678 -4.417769  0.544578  0.931146  1.151816 -0.342553  0.125665   
1774  0.762953  0.643399  3.119026 -0.449233 -2.038239 -0.268279 -0.225335   
1775 -0.433045  3.216018  2.011168 -0.229289 -1.509359 -1.166807 -2.852443   
1776 -0.525867 -1.154642 -1.889819  0.953331  0.807078 -1.084715  1.495877   
1777  5.106682 -0.289142  0.341407 -1.773523 -2.469448  1.596729  0.885051   
1778  5.900098 -1.710240  1.858915  0.171253 -4.529248  4.714808  0.440302   
1779  1.597139  4.676427  0.469293 -0.503399 -0.074202 -1.780281 -2.551047   
1780 -5.137834 -0.191049  2.223967  2.046425 -0.885014  3.406911 -0.342168   
1781 -1.416098 -1.031485  1.196076  0.841545 -2.197924  2.483196  0.573307   
1782 -4.272989 -1.355840  3.059714  0.367666  1.045035  0.747243  0.006417   
1783 -3.136887 -1.411700  2.238424 -0.085145  0.779780  0.689974 -1.289873   
1784  1.568544 -0.438604 -1.840595 -0.847230  0.413571 -1.193728  2.474055   
1785  0.058277  1.978137  1.807598  1.282992 -1.856844 -0.847035 -3.167589   
1786 -0.711454  0.253346 -2.934788

In [11]:
pca.explained_variance_ratio_


array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.01347969, 0.01271931, 0.01165837, 0.01057645, 0.00975315,
       0.00944556, 0.00863011, 0.00836632, 0.0079768 , 0.0074645 ,
       0.00725548, 0.0069188 , 0.00653878, 0.00640766, 0.00591378,
       0.00571144, 0.00523517, 0.00481513, 0.00453228, 0.00423061])

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)


In [14]:
model=LogisticRegression()
model.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
pred=model.predict(principalDf_test)
pred

array([8, 3, 0, 4, 9, 6, 6, 8, 3, 7, 4, 0, 2, 5, 4, 5, 8, 6, 5, 1, 2, 1,
       5, 4, 7, 5, 6, 2, 6, 5, 2, 0, 2, 4, 7, 3, 0, 9, 0, 4, 9, 1, 5, 3,
       3, 0, 1, 7, 5, 3, 3, 2, 7, 1, 1, 8, 9, 2, 4, 2, 5, 6, 4, 1, 5, 1,
       8, 4, 5, 3, 7, 4, 8, 2, 7, 4, 5, 4, 9, 6, 0, 1, 6, 0, 7, 9, 2, 5,
       7, 2, 6, 5, 8, 2, 5, 5, 7, 9, 3, 2, 3, 2, 6, 5, 3, 0, 7, 9, 6, 4,
       0, 2, 3, 0, 8, 7, 6, 9, 6, 7, 4, 9, 3, 4, 6, 4, 3, 6, 0, 0, 3, 9,
       1, 1, 3, 7, 1, 5, 1, 4, 6, 5, 3, 2, 2, 6, 9, 8, 3, 9, 5, 7, 0, 4,
       1, 3, 1, 6, 2, 1, 7, 0, 8, 6, 1, 3, 3, 9, 8, 0, 8, 6, 7, 7, 8, 3,
       3, 2, 2, 4, 5, 5, 6, 6, 4, 4, 6, 1, 2, 8, 4, 8, 9, 8, 4, 5, 2, 5,
       8, 8, 0, 4, 9, 0, 3, 3, 1, 0, 2, 9, 8, 9, 7, 2, 7, 1, 5, 2, 1, 8,
       8, 9, 5, 1, 5, 9, 6, 8, 3, 3, 1, 9, 1, 7, 6, 4, 5, 0, 1, 3, 3, 1,
       1, 8, 0, 9, 8, 7, 1, 1, 5, 7, 0, 7, 8, 4, 3, 3, 0, 9, 7, 5, 3, 5,
       3, 4, 4, 8, 8, 3, 3, 3, 7, 8, 7, 4, 7, 4, 0, 1, 6, 1, 6, 7, 9, 1,
       1, 1, 4, 8, 8, 0, 6, 3, 3, 4, 1, 1, 4, 8, 1,

In [16]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9444444444444444

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        48
          1       0.95      0.95      0.95        62
          2       0.98      1.00      0.99        43
          3       0.98      0.93      0.95        67
          4       0.96      0.91      0.93        53
          5       0.92      0.95      0.94        61
          6       1.00      0.97      0.98        58
          7       0.94      0.96      0.95        47
          8       0.83      0.90      0.87        50
          9       0.88      0.90      0.89        51

avg / total       0.95      0.94      0.94       540



In [0]:
from sklearn.metrics import confusion_matrix


In [19]:
confusion_matrix(y_test,pred)


array([[48,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 59,  0,  0,  0,  0,  0,  0,  2,  1],
       [ 0,  0, 43,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 62,  0,  2,  0,  0,  3,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  2,  1,  2],
       [ 0,  0,  0,  0,  0, 58,  0,  0,  0,  3],
       [ 0,  0,  0,  0,  2,  0, 56,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0, 45,  1,  0],
       [ 0,  2,  1,  0,  0,  1,  0,  1, 45,  0],
       [ 0,  1,  0,  0,  0,  2,  0,  0,  2, 46]])