[View in Colaboratory](https://colab.research.google.com/github/kamini25singh/assignment/blob/master/Assignment_14.ipynb)

In [0]:
from sklearn import model_selection
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data")
df

B  1  1.1  1.2  1.3
0    R  1    1    1    2
1    R  1    1    1    3
2    R  1    1    1    4
3    R  1    1    1    5
4    R  1    1    2    1
5    R  1    1    2    2
6    R  1    1    2    3
7    R  1    1    2    4
8    R  1    1    2    5
9    R  1    1    3    1
10   R  1    1    3    2
11   R  1    1    3    3
12   R  1    1    3    4
13   R  1    1    3    5
14   R  1    1    4    1
15   R  1    1    4    2
16   R  1    1    4    3
17   R  1    1    4    4
18   R  1    1    4    5
19   R  1    1    5    1
20   R  1    1    5    2
21   R  1    1    5    3
22   R  1    1    5    4
23   R  1    1    5    5
24   L  1    2    1    1
25   B  1    2    1    2
26   R  1    2    1    3
27   R  1    2    1    4
28   R  1    2    1    5
29   B  1    2    2    1
..  .. ..  ...  ...  ...
594  L  5    4    5    1
595  L  5    4    5    2
596  L  5    4    5    3
597  B  5    4    5    4
598  R  5    4    5    5
599  L  5    5    1    1
600  L  5    5    1    2
601  L  5    5    1    3
602  L  5    5    1    4
603  L  5    5    1    5
604  L  5    5    2    1
605  L  5    5    2    2
606  L  5    5    2    3
607  L  5    5    2    4
608  L  5    5    2    5
609  L  5    5    3    1
610  L  5    5    3    2
611  L  5    5    3    3
612  L  5    5    3    4
613  L  5    5    3    5
614  L  5    5    4    1
615  L  5    5    4    2
616  L  5    5    4    3
617  L  5    5    4    4
618  L  5    5    4    5
619  L  5    5    5    1
620  L  5    5    5    2
621  L  5    5    5    3
622  L  5    5    5    4
623  B  5    5    5    5

[624 rows x 5 columns]

In [3]:
df.head()


B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [4]:
df.shape


(624, 5)

In [0]:
X=df.drop(["B"],axis=1)
Y=df["B"]

In [0]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)


In [0]:
from sklearn import tree


In [0]:
model=tree.DecisionTreeClassifier(max_leaf_nodes=10)


In [9]:
model.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=10,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
pred = model.predict(X_test)


In [11]:
from sklearn import metrics
metrics.accuracy_score(Y_test,pred)

0.744

In [12]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00         9
          L       0.74      0.82      0.78        62
          R       0.75      0.78      0.76        54

avg / total       0.69      0.74      0.72       125



/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
from sklearn.metrics import confusion_matrix


In [14]:
confusion_matrix(Y_test,pred)


array([[ 0,  6,  3],
       [ 0, 51, 11],
       [ 0, 12, 42]])

In [0]:
model1=tree.DecisionTreeClassifier(criterion="entropy",max_depth=10)


In [16]:
model1.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
pred1 = model1.predict(X_test)


In [18]:
metrics.accuracy_score(Y_test,pred1)


0.792

In [19]:

print(classification_report(Y_test,pred1))


             precision    recall  f1-score   support

          B       0.00      0.00      0.00         9
          L       0.86      0.87      0.86        62
          R       0.90      0.83      0.87        54

avg / total       0.81      0.79      0.80       125



In [20]:
confusion_matrix(Y_test,pred1)


array([[ 0,  5,  4],
       [ 7, 54,  1],
       [ 5,  4, 45]])

In [0]:

from sklearn.ensemble import RandomForestClassifier


In [0]:
model2=RandomForestClassifier(random_state=1,max_depth=10 )


In [23]:

model2.fit(X_train,Y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [0]:
pred2 = model2.predict(X_test)


In [25]:
metrics.accuracy_score(Y_test,pred2)


0.832

In [26]:
print(classification_report(Y_test,pred2))


             precision    recall  f1-score   support

          B       0.00      0.00      0.00         9
          L       0.88      0.94      0.91        62
          R       0.85      0.85      0.85        54

avg / total       0.80      0.83      0.82       125



In [27]:
confusion_matrix(Y_test,pred2)


array([[ 0,  3,  6],
       [ 2, 58,  2],
       [ 3,  5, 46]])

In [0]:
model3=RandomForestClassifier(criterion="entropy")


In [29]:
model3.fit(X_train,Y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [0]:


pred3 = model3.predict(X_test)


In [31]:
metrics.accuracy_score(Y_test,pred3)


0.8

In [32]:
print(classification_report(Y_test,pred3))


             precision    recall  f1-score   support

          B       0.00      0.00      0.00         9
          L       0.83      0.92      0.87        62
          R       0.90      0.80      0.84        54

avg / total       0.80      0.80      0.80       125



In [33]:

confusion_matrix(Y_test,pred3)


array([[ 0,  6,  3],
       [ 3, 57,  2],
       [ 5,  6, 43]])