[View in Colaboratory](https://colab.research.google.com/github/kamini25singh/assignment/blob/master/Assignment_16.ipynb)

In [0]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline
from sklearn.svm import SVC

In [0]:
from sklearn.datasets import load_wine


In [0]:
wine=load_wine()
x=(wine.data)
y=(wine.target)

In [7]:
x.shape,y.shape


((178, 13), (178,))

In [0]:
from sklearn.ensemble import BaggingClassifier


In [0]:
from sklearn import tree


In [0]:
model=tree.DecisionTreeClassifier()


In [0]:
num_trees=100

In [0]:
model1=BaggingClassifier(base_estimator=model)


In [13]:
model1



BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)


In [16]:
model1.fit(x_train,y_train)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [0]:

pred=model1.predict(x_test)


In [18]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9722222222222222

In [19]:

from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.92      0.96        12
          1       0.93      1.00      0.96        13
          2       1.00      1.00      1.00        11

avg / total       0.97      0.97      0.97        36



In [0]:
from sklearn.metrics import confusion_matrix


In [21]:
confusion_matrix(y_test,pred)


array([[11,  1,  0],
       [ 0, 13,  0],
       [ 0,  0, 11]])

In [0]:
from sklearn.ensemble import RandomForestClassifier


In [0]:
model2=RandomForestClassifier(random_state=1,max_depth=10 )


In [24]:
model2.fit(x_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [0]:
pred1=model2.predict(x_test)


In [26]:
metrics.accuracy_score(y_test,pred1)


0.9444444444444444

In [27]:

print(classification_report(y_test,pred1))


             precision    recall  f1-score   support

          0       0.92      0.92      0.92        12
          1       0.92      0.92      0.92        13
          2       1.00      1.00      1.00        11

avg / total       0.94      0.94      0.94        36



In [28]:
confusion_matrix(y_test,pred1)


array([[11,  1,  0],
       [ 1, 12,  0],
       [ 0,  0, 11]])

In [0]:
from sklearn.ensemble import GradientBoostingClassifier


In [30]:
model3=GradientBoostingClassifier()
model3

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [31]:
model3.fit(x_train,y_train)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [0]:
pred2=model3.predict(x_test)


In [33]:
metrics.accuracy_score(y_test,pred2)


0.9722222222222222

In [34]:
confusion_matrix(y_test,pred2)


array([[11,  1,  0],
       [ 0, 13,  0],
       [ 0,  0, 11]])

In [35]:
print(classification_report(y_test,pred2))


             precision    recall  f1-score   support

          0       1.00      0.92      0.96        12
          1       0.93      1.00      0.96        13
          2       1.00      1.00      1.00        11

avg / total       0.97      0.97      0.97        36



In [0]:
model4=LogisticRegression()
model5=tree.DecisionTreeClassifier()
model6=SVC()

In [0]:
estimators=[]


In [0]:

estimators.append(('logistic',model4))
estimators.append(('cart',model5))
estimators.append(('svm',model6))

In [0]:

from sklearn.ensemble import VotingClassifier


In [0]:
ensemble=VotingClassifier(estimators)


In [41]:
ensemble.fit(x_train,y_train)


VotingClassifier(estimators=[('logistic', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('cart',...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [42]:


pred4=ensemble.predict(x_test)


/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [43]:
metrics.accuracy_score(y_test,pred4)


0.8888888888888888

In [44]:
confusion_matrix(y_test,pred4)


array([[10,  2,  0],
       [ 1, 12,  0],
       [ 0,  1, 10]])

In [45]:
print(classification_report(y_test,pred4))


             precision    recall  f1-score   support

          0       0.91      0.83      0.87        12
          1       0.80      0.92      0.86        13
          2       1.00      0.91      0.95        11

avg / total       0.90      0.89      0.89        36

